version: "3.9"
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  init-kafka-topic:
    image: bitnami/kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
      kafka-topics.sh --bootstrap-server kafka:9092 --create --topic demo-topic --partitions 1 --replication-factor 1 || true
      "
    restart: "no"

  producer:
    build: ./producer
    volumes:
      - ./producer:/app # makes local code live inside the container (may not work on WSL)
    ports:
      - 3000:3000 # container:3000 to host:3000
    depends_on:
      - init-kafka-topic
    environment:
      - MAX_BATCH_SIZE=10000
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=demo-topic
      - CLIENT_ID=demo-producer
      - PORT=3000
    command: ["bun", "--hot", "index.ts"] # hot reload on code change (may not work on WSL)
    restart: unless-stopped

  consumer:
    build: ./consumer
    volumes:
      - ./consumer:/app
    depends_on:
      - init-kafka-topic
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=demo-topic
      - CLIENT_ID=demo-consumer
      - PORT=3000
    command: ["bun", "--hot", "index.ts"]
    restart: unless-stopped
